# Generated by Django 4.0.2 on 2022-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_folie', models.CharField(
                    choices=[('MICRO', 'Microperforata'), ('MACRO', 'Macroperforata'), ('SIMPLU', 'Neperforata')],
                    default='SIMPLU', max_length=6, verbose_name='Tipul foliei')),
                ('grosime_folie', models.PositiveBigIntegerField(verbose_name='Grosime Folie(um)')),
                ('latime_folie', models.PositiveBigIntegerField(verbose_name='Latime Folie(mm)')),
                ('cantitate', models.PositiveBigIntegerField(null=True, verbose_name='Nr. kilograme')),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pungi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_punga', models.CharField(
                    choices=[('Stand-Up', 'Stand-Up'), ('3 Side Seal', '3 Side Seal'), ('Pentru Cafea', 'Pentru Cafea'),
                             ('Pentru Fructe / Legume', 'Pentru fructe/legume')], default='Stand-Up', max_length=22,
                    verbose_name='Tipul Pungii')),
                ('inaltime_punga', models.PositiveBigIntegerField(verbose_name='Inaltime Punga(mm)')),
                ('latime_punga', models.PositiveBigIntegerField(verbose_name='Latime Punga(mm)')),
                ('inaltime_pliu', models.PositiveBigIntegerField(verbose_name='Inaltime Pliu(mm)')),
                ('grosime_folie_p', models.PositiveBigIntegerField(verbose_name='Grosime Folie(um)')),
                ('zipper', models.BooleanField()),
                ('eurohole', models.BooleanField()),
                ('ciupitura', models.BooleanField()),
                ('cantitate', models.PositiveBigIntegerField(null=True, verbose_name='Nr. Bucati(min. 10.000 buc)')),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produs', models.CharField(max_length=100)),
                ('tip_produs', models.CharField(max_length=100)),
            ],
        ),
    ]
