# Generated by Django 4.0.2 on 2022-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_folie', models.CharField(max_length=100)),
                ('grosime_folie', models.CharField(max_length=100)),
                ('latime_folie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pungi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_punga', models.CharField(max_length=100)),
                ('inaltime_punga', models.CharField(max_length=100)),
                ('latime_punga', models.CharField(max_length=100)),
                ('inaltime_pliu', models.CharField(max_length=100)),
                ('grosime_folie_p', models.CharField(max_length=100)),
            ],
        ),
    ]
