# Generated by Django 4.0.2 on 2022-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_folie_pungi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folie',
            name='grosime_folie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='folie',
            name='latime_folie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='grosime_folie_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_pliu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_punga',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='latime_punga',
            field=models.IntegerField(default=0),
        ),
    ]
