# Generated by Django 4.0.2 on 2022-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_folie_grosime_folie_alter_folie_latime_folie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pungi',
            name='ciupitura',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pungi',
            name='eurohole',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pungi',
            name='zipper',
            field=models.BooleanField(null=True),
        ),
    ]
