# Generated by Django 4.0.2 on 2022-02-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_pungi_ciupitura_pungi_eurohole_pungi_zipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='folie',
            name='cantitate',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Nr. kilograme'),
        ),
        migrations.AddField(
            model_name='pungi',
            name='cantitate',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Nr. Bucati'),
        ),
        migrations.AlterField(
            model_name='folie',
            name='grosime_folie',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Grosime Folie(um)'),
        ),
        migrations.AlterField(
            model_name='folie',
            name='latime_folie',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Latime Folie(mm)'),
        ),
        migrations.AlterField(
            model_name='folie',
            name='tip_folie',
            field=models.CharField(choices=[('MICRO', 'Microperforata'), ('MACRO', 'Macroperforata'), ('SIMPLU', 'Neperforata')], default='SIMPLU', max_length=6, verbose_name='Tipul foliei'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='ciupitura',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='eurohole',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='grosime_folie_p',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Grosime Folie(um)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_pliu',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Inaltime Pliu(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_punga',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Inaltime Punga(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='latime_punga',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Latime Punga(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='tip_punga',
            field=models.CharField(choices=[('Stand-Up', 'Stand-Up'), ('3 Side Seal', '3 Side Seal'), ('Pentru Cafea', 'Pentru Cafea'), ('Pentru Fructe / Legume', 'Pentru frucete/legume')], default='Stand-Up', max_length=22, verbose_name='Tipul Pungii'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='zipper',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
