# Generated by Django 4.0.2 on 2022-02-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_folie_cantitate_pungi_cantitate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folie',
            name='cantitate',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Nr. kilograme'),
        ),
        migrations.AlterField(
            model_name='folie',
            name='grosime_folie',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Grosime Folie(um)'),
        ),
        migrations.AlterField(
            model_name='folie',
            name='latime_folie',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Latime Folie(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='cantitate',
            field=models.PositiveBigIntegerField(default=10000, verbose_name='Nr. Bucati (min. 10.000 buc)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='eurohole',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='grosime_folie_p',
            field=models.PositiveBigIntegerField(verbose_name='Grosime Folie(um)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_pliu',
            field=models.PositiveBigIntegerField(verbose_name='Inaltime Pliu(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='inaltime_punga',
            field=models.PositiveBigIntegerField(verbose_name='Inaltime Punga(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='latime_punga',
            field=models.PositiveBigIntegerField(verbose_name='Latime Punga(mm)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='zipper',
            field=models.BooleanField(null=True),
        ),
    ]
