# Generated by Django 4.0.2 on 2022-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_folie_cantitate_alter_folie_grosime_folie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pungi',
            name='cantitate',
            field=models.PositiveBigIntegerField(verbose_name='Nr. Bucati (min. 10.000 buc)'),
        ),
        migrations.AlterField(
            model_name='pungi',
            name='tip_punga',
            field=models.CharField(choices=[('Stand-Up', 'Stand-Up'), ('3 Side Seal', '3 Side Seal'), ('Pentru Cafea', 'Pentru Cafea'), ('Pentru Fructe / Legume', 'Pentru fructe/legume')], default='Stand-Up', max_length=22, verbose_name='Tipul Pungii'),
        ),
    ]
